development:
  adapter: postgresql
  encoding: unicode
  database: sinatra_app_development

test:
  adapter: postgresql
  encoding: unicode
  database: sinatra_app_test

production:
  adapter: postgresql
  encoding: unicode
  database: sinatra_app_production